### ISSUE TITLE
how do you run this thing ? :)

### ISSUE THREAD

**Issue by sokoow** [xames3/charlotte#1]
hey, nice project, but how do you run it ?

**Comment by stardust-xs** [comment]
Hello @sokoow ,

Glad you find this project interesting. This is a NLP (Chatbot) project based on [Rasa](https://github.com/RasaHQ/rasa). And to be honest this project is still under development so I haven't added much to the README. Once I'm done with some considerable amount of work, I shall update the steps.

If you any questions, please feel free to fire them as I'm open for suggestions. 😃

**Comment by sokoow** [comment]
Just starting with rasa, my first day, and I bumped into your project. Was just curious cause it's one of the most complete ones I found, despite it's docs. Greetings.

**Comment by stardust-xs** [comment]
Oh in that case, welcome... 😃

Since you're starting off with it, I highly suggest you to read their docs [here](https://rasa.com/docs/rasa/) as every* Rasa user uses it for reference. Also one very important tip, watch their on-going YouTube playlist [here](https://www.youtube.com/playlist?list=PL75e0qA87dlHQny7z43NduZHPo6qd-cRc). This will really help you while starting off with Rasa.

And if you need any help, please do let me know. I will try to help you or post your query on their community [forum](https://forum.rasa.com/). Its quite active! 😃
